[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
shop_cart = "Ghjt9quQKYs9yHANEUaVHPaBFfmhTECeERSKU9q9SjKa"

[programs.devnet]
shop_cart = "Ghjt9quQKYs9yHANEUaVHPaBFfmhTECeERSKU9q9SjKa"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "devnet"
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
